#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Render the due-diligence corpus: single source of truth = tools/data_*.py
Emits (all generated, do not hand-edit):
  data/projects/<slug>.json   machine-readable record, 10 required fields
  data/projects/<slug>.md     same record, Thai prose for humans
  data/index.json             fast scan index for agents
  data/scorecard.csv          one row per project (Excel-friendly, UTF-8 BOM)
  docs/schema.json            JSON Schema enforcing the 10 fields
  README.md                   ranking + money ladders + how to consume this repo

Usage:  python3 tools/build.py [--check]     (--check = validate only, write nothing)
"""
import csv, io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from data_renaiss import PROJECTS as _A
from data_netnet_pullfun import PROJECTS as _B
from data_older import PROJECTS as _C
from data_meta import META

SCHEMA_VERSION = "1.0"
GENERATED_NOTE = "generated by tools/build.py — source of truth is tools/data_*.py, edit there then rebuild"

# The 10 fields the reader (human or agent) must be able to answer from every record.
FIELDS = [
 ("1", "project + X link",            ["name", "aliases", "links.x"]),
 ("2", "interest level",              ["score.interest", "field2_interest"]),
 ("3", "credibility / trust",         ["score.trust", "trust_evidence[]"]),
 ("4", "model / architecture",        ["model", "legal_entity", "chain"]),
 ("5", "how to play or invest",       ["how_to_play[]"]),
 ("6", "risks",                       ["risks[]"]),
 ("7", "value for money",             ["value_for_money", "house_edge[]", "cost_of_entry_usd"]),
 ("8", "opportunity + returns",       ["opportunity", "returns[]", "max_sane_budget_usd", "capital_rule"]),
 ("9", "history + technical/on-chain", ["history[]", "technical", "verified_on"]),
 ("10", "short verdict",              ["verdict_short", "status", "rank"]),
]
REQUIRED = ["slug", "name", "links", "score", "field2_interest", "trust_evidence", "model",
            "how_to_play", "risks", "value_for_money", "house_edge", "opportunity", "returns",
            "history", "technical", "verdict_short", "unverified", "watch", "sources",
            "status", "rank", "legal_entity", "chain", "stale_risk", "verified_on",
            "cost_of_entry_usd", "max_sane_budget_usd", "capital_rule"]

LABELS = {
 "1": "1) ชื่อโปรเจกต์ + ลิงก์ X", "2": "2) ระดับความน่าสนใจ (interest score)",
 "3": "3) ความน่าเชื่อถือ (credibility) + หลักฐาน", "4": "4) โมเดล / สถาปัตยกรรม",
 "5": "5) วิธีเล่น / วิธีลงทุน", "6": "6) ความเสี่ยง", "7": "7) ความคุ้มค่า (เงินที่จ่าย vs สิ่งที่ได้)",
 "8": "8) โอกาส + ผลตอบแทนคาดการณ์ตามงบ", "9": "9) ประวัติ + การวิเคราะห์ทางเทคนิค/on-chain",
 "10": "10) สรุปสั้น",
}


def load():
    recs = {}
    for src in (_A, _B, _C):
        recs.update(src)
    for slug, rec in recs.items():
        if slug not in META:
            raise SystemExit(f"build.py: {slug} missing entry in tools/data_meta.py")
        m = dict(META[slug])
        rec["value_for_money"] = m["value_for_money"]
        rec["cost_of_entry_usd"] = m["budget_min_usd"]
        rec["max_sane_budget_usd"] = m["budget_max_sane_usd"]
        rec["capital_rule"] = m["capital_rule"]
        rec["verified_on"] = m["verified_on"]
        sr = str(rec.get("stale_risk", ""))
        if "\u2014" in sr:                       # "level — reason" in the source data -> split for the schema enum
            lvl, note = [x.strip() for x in sr.split("\u2014", 1)]
            rec["stale_risk"], rec["stale_risk_note"] = lvl, note
        rec["needs_recheck"] = rec.get("links", {}).get("x") in (None, "") or "ไม่ถูกบันทึก" in " ".join(map(str, rec.get("history", [])))
        rec["schema_version"] = SCHEMA_VERSION
        rec["generated_from"] = GENERATED_NOTE
    order = sorted(recs.values(), key=lambda r: r["rank"])
    for i, r in enumerate(order, 1):
        r["rank"] = i
    return {r["slug"]: r for r in order}


def validate(recs):
    problems = []
    for slug, r in recs.items():
        for k in REQUIRED:
            if k not in r or r[k] in (None, "", [], {}):
                if not (k == "links" and True):
                    problems.append(f"{slug}: missing/empty required key '{k}'")
        for s in ("interest", "trust"):
            v = r.get("score", {}).get(s)
            if not isinstance(v, (int, float)) or not 0 <= v <= 10:
                problems.append(f"{slug}: score.{s}={v!r} out of range 0..10")
        budgets = [x.get("budget_usd") for x in r.get("returns", [])]
        if len(budgets) < 4 or budgets != sorted(budgets):
            problems.append(f"{slug}: returns[] must be >=4 rungs sorted by budget_usd (got {budgets})")
        if not r.get("unverified"):
            problems.append(f"{slug}: unverified[] is mandatory (honesty field)")
        if not r.get("technical", {}).get("onchain"):
            problems.append(f"{slug}: technical.onchain[] empty")
    return problems


def to_json_record(r):
    """Stable key order: identity -> scores -> 10 fields -> evidence -> meta."""
    keys = ["slug", "schema_version", "name", "aliases", "rank", "status", "links", "chain", "legal_entity",
            "score", "field2_interest", "trust_evidence", "model", "how_to_play", "risks",
            "value_for_money", "house_edge", "cost_of_entry_usd", "opportunity", "returns",
            "max_sane_budget_usd", "capital_rule", "history", "technical", "verdict_short",
            "unverified", "watch", "needs_recheck", "stale_risk", "stale_risk_note", "verified_on", "sources", "generated_from"]
    return {k: r[k] for k in keys if k in r}


def bullets(items, prefix="- "):
    return "\n".join(f"{prefix}{i}" for i in items) if items else "- (ไม่มีข้อมูล)"


def md_for(r):
    L = []
    a = L.append
    a(f"# {r['name']} — ผลการตรวจสอบ (Due Diligence)")
    a("")
    a(f"> {GENERATED_NOTE} · `verified_on: {r['verified_on']}` · `stale_risk: {r['stale_risk']}`"
      f" ({r.get('stale_risk_note', '')})"
      + (" · **needs_recheck: true** (ข้อมูลบางส่วนไม่ครบถ้วน ให้ re-derive ก่อนอ้างอิง)" if r["needs_recheck"] else ""))
    a("")
    a("## คำตอบสั้น (field 10)")
    a("")
    a(r["verdict_short"])
    a("")
    a("| อันดับ | interest | credibility | สถานะ | ต้นทุนเข้าต่ำสุด | งบสูงสุดที่สมเหตุสมผล |")
    a("|---:|---:|---:|---|---:|---:|")
    a(f"| {r['rank']} | {r['score']['interest']}/10 | {r['score']['trust']}/10 | {r['status']} "
      f"| ${r['cost_of_entry_usd']:,} | ${r['max_sane_budget_usd']:,} |")
    a("")
    a("## 1) โปรเจกต์ + ลิงก์")
    a("")
    a(f"- ชื่อ: **{r['name']}**" + (f" (aliases: {', '.join(r['aliases'])})" if r.get("aliases") else ""))
    a(f"- X: {r['links'].get('x') or '— *ยังไม่ยืนยัน handle ทางการ*'}")
    for k, v in r["links"].items():
        if k == "x" or not v:
            continue
        if isinstance(v, list):
            a(f"- {k}: " + ", ".join(v))
        else:
            a(f"- {k}: {v}")
    a(f"- เชน: {r['chain']}")
    a(f"- นิติบุคคล: {r['legal_entity']}")
    a("")
    a(f"## 2) ระดับความน่าสนใจ — {r['score']['interest']}/10")
    a("")
    a(r["field2_interest"])
    a("")
    a(f"## 3) ความน่าเชื่อถือ — {r['score']['trust']}/10")
    a("")
    a(bullets(r["trust_evidence"], "- ✅ "))
    a("")
    a("## 4) โมเดล / สถาปัตยกรรม")
    a("")
    a(r["model"])
    a("")
    a("## 5) วิธีเล่น / วิธีลงทุน (เรียงตามนี้)")
    a("")
    a(bullets(r["how_to_play"], "1. "))
    a("")
    a("## 6) ความเสี่ยง")
    a("")
    a(bullets(r["risks"], "- ⚠️ "))
    a("")
    a("## 7) ความคุ้มค่า (เงินที่จ่าย vs สิ่งที่ได้)")
    a("")
    a(r["value_for_money"])
    a("")
    a("| เครื่อง/องค์ประกอบ | ราคา/งบ (USD) | มูลค่าที่คาดว่าจะได้กลับ | EV เทียบราคา | ขายกลับทันที (net) |")
    a("|---|---:|---:|---:|---:|")
    for h in r["house_edge"]:
        name = h.get("machine") or h.get("component") or "-"
        price = h.get("price_usd")
        ev = h.get("ev_usd")
        a(f"| {name} | {'' if price is None else f'${price:,}'} | {'' if ev is None else f'${ev:,.2f}'} "
          f"| {h.get('ev_over_price', '—')} | {'—' if h.get('instant_flip_net_pct') is None else str(h['instant_flip_net_pct']) + '%'} |")
    a("")
    a(f"ต้นทุนเข้าขั้นต่ำที่ทดสอบได้: ${r['cost_of_entry_usd']:,}")
    a("")
    a("## 8) โอกาส + ผลตอบแทนคาดการณ์ตามงบ")
    a("")
    a(r["opportunity"])
    a("")
    a("| งบ (USD) | สิ่งที่ทำ | ผลลัพธ์คาดการณ์ (USD) | หมายเหตุ |")
    a("|---:|---|---:|---|")
    for x in r["returns"]:
        note = x.get("note", "")
        what = note.split(" — ")[0][:60]
        exp = x.get("expected_usd")
        exp = "—" if exp is None else f"{exp:+,.0f}"
        a(f"| {x['budget_usd']:,} | {what} | {exp} | {note} |")
    a("")
    a(f"**เพดานงบที่สมเหตุสมผล: ${r['max_sane_budget_usd']:,}** — {r['capital_rule']}")
    a("")
    a("## 9) ประวัติ + หลักฐานทางเทคนิค/on-chain")
    a("")
    a("### ไทม์ไลน์")
    a(bullets(r["history"], "- "))
    a("")
    a("### สิ่งที่วัดได้จริง")
    for t in r["technical"].get("onchain", []):
        addr = t.get("addr")
        a(f"- **{t['item']}**" + (f" `{addr}`" if addr else "") + f" — {t['finding']}")
    eps = r["technical"].get("api_endpoints")
    if eps:
        a("")
        a("### จุดที่เรียกตรวจสอบได้")
        a(bullets(eps, "- `")) if False else a("\n".join(f"- `{e}`" for e in eps))
    acc = r["technical"].get("accounts") or {}
    if acc:
        a("")
        a("### บัญชี/สถานะตลาด")
        for k, v in acc.items():
            if isinstance(v, dict):
                a(f"- {k}: " + ", ".join(f"{kk}={vv}" for kk, vv in v.items()))
            else:
                a(f"- {k}: {v}")
    mkt = r["technical"].get("market") or {}
    if mkt:
        a("")
        a("### ตลาด / โทเคน")
        for k, v in mkt.items():
            a(f"- {k}: {v}")
    a("")
    a("## สิ่งที่ยังตรวจสอบไม่ได้ (ห้ามอ่านข้าม)")
    a("")
    a(bullets(r["unverified"], "- ❓ "))
    a("")
    a("## ต้องเฝ้าต่อ")
    a("")
    a(bullets(r["watch"], "- 👀 "))
    a("")
    a("## แหล่งอ้างอิง")
    a("")
    a(bullets(r["sources"], "- "))
    a("")
    a("---")
    a("ข้อจำกัด: ตัวเลขทั้งหมดเป็น snapshot ณ วันตรวจ และ platform claims ไม่ถูกถือเป็นเรื่องจริงจนกว่าจะ verify on-chain — ดู `docs/pitfalls.md`")
    a("")
    return "\n".join(L)


def index_for(recs):
    return {
     "schema_version": SCHEMA_VERSION,
     "generated_by": "tools/build.py",
     "as_of": "2026-09-30",
     "language": "th",
     "reading_guide": "AGENTS.md",
     "fields_per_project": [{"n": n, "field": d, "keys": k} for n, d, k in FIELDS],
     "projects": [
      {"slug": r["slug"], "name": r["name"], "rank": r["rank"], "x": r["links"].get("x"),
       "interest": r["score"]["interest"], "credibility": r["score"]["trust"],
       "status": r["status"], "verdict_short": r["verdict_short"],
       "cost_of_entry_usd": r["cost_of_entry_usd"], "max_sane_budget_usd": r["max_sane_budget_usd"],
       "needs_recheck": r["needs_recheck"], "verified_on": r["verified_on"], "stale_risk": r["stale_risk"],
       "json": f"data/projects/{r['slug']}.json", "md": f"data/projects/{r['slug']}.md"}
      for r in sorted(recs.values(), key=lambda x: x["rank"])],
    }


def csv_rows(recs):
    hdr = ["rank", "slug", "name", "interest_0_10", "credibility_0_10", "status", "needs_recheck",
           "cost_of_entry_usd", "max_sane_budget_usd", "ev_at_100usd", "ev_at_1000usd",
           "verified_on", "stale_risk", "x_handle", "one_line_verdict"]
    rows = [hdr]
    for r in sorted(recs.values(), key=lambda x: x["rank"]):
        def ev(b):
            best, d = 0.0, 10 ** 9
            for x in r["returns"]:
                dd = abs(x["budget_usd"] - b)
                if dd < d:
                    d, best = dd, x.get("expected_usd", 0.0)
            return "" if best is None else f"{best:+.0f}"
        rows.append([r["rank"], r["slug"], r["name"], r["score"]["interest"], r["score"]["trust"], r["status"],
                     str(r["needs_recheck"]).lower(), r["cost_of_entry_usd"], r["max_sane_budget_usd"],
                     ev(100), ev(1000), r["verified_on"], r["stale_risk"], r["links"].get("x") or "",
                     r["verdict_short"].replace("\n", " ")])
    return rows


def matrix(recs):
    budgets = [0, 100, 500, 1000, 5000, 10000]
    order = sorted(recs.values(), key=lambda x: x["rank"])
    out = ["| งบ | " + " | ".join(r["name"] for r in order) + " |", "|---:" + "|---:" * len(order)]
    for b in budgets:
        cells = []
        for r in order:
            best, d = None, 10 ** 9
            for x in r["returns"]:
                dd = abs(x["budget_usd"] - b)
                if dd < d:
                    d, best = dd, x.get("expected_usd")
            cells.append("—" if best is None else f"{best:+,.0f}")
        out.append(f"| ${b:,} | " + " | ".join(cells) + " |")
    return "\n".join(out)


def readme(recs):
    order = sorted(recs.values(), key=lambda x: x["rank"])
    L = []
    a = L.append
    a("# Crypto / NFT / points due-diligence — อ่านได้ทั้งคนและ agent")
    a("")
    a("ตรวจเองบนเชน+API ไม่เชื่อข้อความบนเว็บ · ภาษาไทย · ทุกตัวเลขมีคำสั่ง re-verify ได้ (`tools/verify.sh`)")
    a("")
    a(f"- 8 โปรเจกต์ · snapshot หลัก: `2026-09-30` · schema `v{SCHEMA_VERSION}`")
    a("- เริ่มอ่านจาก: `llms.txt` (agent) หรือตารางด้านล่าง (คน)")
    a("- แก้ข้อมูล: แก้ `tools/data_*.py` → `python3 tools/build.py` (ไฟล์อื่นทั้งหมดถูก generate) ")
    a("")
    a("## การจัดอันดับ (interest = ความน่าสนใจ, credibility = ความน่าเชื่อถือ)")
    a("")
    a("| # | โปรเจกต์ | interest | credibility | สถานะ | เข้าได้ตั้งแต่ | เพดานงบ | หนึ่งบรรทัด |")
    a("|--:|---|--:|--:|---|--:|--:|---|")
    for r in order:
        v = r["verdict_short"].replace("\n", " ")
        v = v if len(v) <= 120 else v[:117] + "…"
        a(f"| {r['rank']} | [{r['name']}](data/projects/{r['slug']}.md) | {r['score']['interest']} "
          f"| {r['score']['trust']} | {r['status'].split(';')[0]} | ${r['cost_of_entry_usd']:,} "
          f"| ${r['max_sane_budget_usd']:,} | {v} |")
    a("")
    a("## ผลตอบแทนคาดการณ์ตามงบ (USD, ค่าคาดหวังหลังหัก house edge/fee แล้ว — ไม่ใช่คำการันตี)")
    a("")
    a(matrix(recs))
    a("")
    a("> อ่านตารางนี้ว่า: ถ้ามีเงิน X ควรไปลงตรงไหน และ **ผลที่คาดหวังเป็น USD** คือเท่าไร; ตัวเลขเชิงลบหมายความว่า "
      "ค่าเฉลี่ยของผู้เล่นเสียเท่านั้นเท่านี้ ไม่ใช่ \"อาจจะเสีย\"")
    a("")
    a("## หลักการให้คะแนน credibility (rubric)")
    a("")
    a("| องค์ประกอบ | น้ำหนัก |")
    a("|---|--:|")
    a("| ตรวจสอบ on-chain ได้จริง | 25 |")
    a("| การ custody เงิน/ของ + หลักฐานสต็อก | 20 |")
    a("| ปริมาณการใช้งานจริง (ไม่ใช่ตัวเลข PR) | 20 |")
    a("| นิติบุคคล + การเปิดเผยใน ToS | 15 |")
    a("| โครงสร้าง tokenomics / house edge เปิดเผย | 10 |")
    a("| ทีม + ผู้สนับสนุน (ยืนยันจากแหล่งอิสระ) | 10 |")
    a("")
    a("คะแนนที่แสดงเป็น 0–10 (ถ่วงน้ำหนักแล้ว ×10) — ดูวิธีคิดเต็ม ๆ ที่ `docs/methodology.md`")
    a("")
    a("## สิ่งที่ไม่ตรวจให้ (ขอบเขต)")
    a("")
    a("- สัญญาว่าเป็นกำไร / ให้คำแนะนำการลงทุนรายบุคคล — นี่คือข้อมูลตัดสินใจ ไม่ใช่คำแนะนำ")
    a("- ตัวเลขที่แพลตฟอร์มไม่เปิดให้วัด (จำนวน holder จริงบน chain ที่ RPC ถูกปิดกั้น, สต็อกในคลัง vault) — ดู `unverified[]` ของแต่ละไฟล์")
    a("")
    a("## โครงสร้างไฟล์")
    a("")
    a("```")
    a("llms.txt                     ทางเข้าของ agent")
    a("AGENTS.md                    กติกาการอ่าน/อัปเดต")
    a("data/index.json              สแกนเร็ว: slug, rank, scores, verdict, path")
    a("data/scorecard.csv           หนึ่งแถวต่อโปรเจกต์ (เปิดใน Excel ได้)")
    a("data/schema.json             JSON Schema — บังคับให้มีครบ 10 ฟิลด์")
    a("data/projects/<slug>.json    บันทึกเต็ม (ทุกฟิลด์ที่ agent ต้องใช้)")
    a("data/projects/<slug>.md      บันทึกเดียวกันฉบับคนอ่าน")
    a("docs/methodology.md          rubric + นิยาม house edge + เกณฑ์ตัดคะแนน")
    a("docs/pitfalls.md             กับดัก/ข้อผิดพลาดที่เคยเกิด (รวมสิ่งที่ผมเคยแก้)")
    a("docs/evidence.md             คำสั่ง + endpoint + contract ที่ใช้พิสูจน์ทีละข้อ")
    a("tools/data_*.py              แหล่งข้อมูลจริง (แก้ที่นี่)")
    a("tools/build.py               ตัว render ทั้งหมดใน repo")
    a("tools/verify.sh              re-verify live ก่อนอ้างตัวเลข")
    a("tools/push-github.sh         สร้าง repo + push (ต้องใส่ GITHUB_TOKEN เอง)")
    a("```")
    a("")
    a("## หมายเหตุความซื่อสัตย์")
    a("")
    a("ทุกไฟล์มี `unverified[]` ของตัวเอง; `needs_recheck: true` = หลักฐานชุดนั้นไม่ครบถ้วนโดยเจตนา (โปรเจกต์ที่ตรวจไว้รอบแรก "
      "และ raw artifacts ไม่ถูกเก็บไว้) — ห้ามใช้อ้างอิงภายนอกถ้ายังไม่ re-derive")
    a("")
    return "\n".join(L)


def llms(recs):
    order = sorted(recs.values(), key=lambda x: x["rank"])
    L = ["# Crypto / NFT / points due-diligence (Thai, agent-readable)", "",
         "งานวิเคราะห์แบบตรวจสอบ-on-chain-of-claims ของโปรเจกต์ที่แชร์กันใน thread ภาษาไทยบน X",
         "ทุก record ตอบ 10 ฟิลด์ภาคบังคับ และทุกตัวเลขต้อง re-verify ก่อนอ้าง (ดูกฎด้านล่าง)", "",
         "## Rules for agents",
         "1. อ่าน `data/index.json` ก่อน (8 แถว) แล้วเปิด `data/projects/<slug>.json` เฉพาะตัวที่ต้องใช้",
         "2. ห้ามอ้างตัวเลขใด ๆ โดยไม่รัน `bash tools/verify.sh` ก่อน — snapshot เก่าได้ (stale_risk ระบุระดับไว้ต่อ record)",
         "3. ห้ามแปล `unverified[]` เป็นข้อสรุปเชิงบวก และห้ามถือว่าข้อความบนเว็บโปรเจกต์เป็นความจริง",
         "4. ถ้า `needs_recheck: true` ให้ถือว่า record นั้นไม่ครบ (หลักฐานรอบแรกไม่ได้เก็บ raw ไว้) — ต้อง re-derive ก่อนใช้",
         "5. เวลาให้คำแนะนำเงิน ใช้ `returns[]` + `capital_rule` + `max_sane_budget_usd` เท่านั้น; อย่าสร้างตัวเลขใหม่",
         "6. อัปเดต = แก้ `tools/data_*.py` แล้วรัน `python3 tools/build.py` (ห้ามแก้ไฟล์ generate โดยตรง)",
         "",
         "## 10 mandatory fields (key mapping)", ""]
    for n, d, keys in FIELDS:
        L.append(f"{n}. {d} → {' / '.join(keys)}")
    L += ["", "## Index", ""]
    for r in order:
        L.append(f"- **{r['rank']}. {r['name']}** (interest {r['score']['interest']}/10, credibility {r['score']['trust']}/10)"
                 f" — {r['status']}: {r['verdict_short'].split(' แต่ ')[0][:150]}")
        L.append(f"  json: `data/projects/{r['slug']}.json` · md: `data/projects/{r['slug']}.md`"
                 f" · verified_on: {r['verified_on']} · needs_recheck: {str(r['needs_recheck']).lower()}")
    L += ["", "## Money summary (expected USD at each budget)", "",
          matrix(recs), "",
          "ไฟล์:", "- `data/scorecard.csv` ตารางเดียวจบ", "- `docs/methodology.md` rubric",
          "- `docs/pitfalls.md` กับดักที่เจอจริง (ใช้ก่อนเริ่มตรวจโปรเจกต์ใหม่)",
          "- `docs/evidence.md` คำสั่งพิสูจน์รายข้อ", ""]
    return "\n".join(L)


def agents_md(recs):
    return f"""# AGENTS.md — วิธีใช้ repo นี้

repo นี้คือ *ฐานข้อมูลผลการตรวจสอบ* ไม่ใช่ blog post. อ่านเป็น JSON/CSV ได้ทันที และทุกความเชื่อมีคำสั่งพิสูจน์แนบไว้

## ถ้าจะอ่านอย่างเดียว
1. `data/index.json` → เลือก slug
2. `data/projects/<slug>.json` → ใช้ 10 ฟิลด์ภาคบังคับ (schema: `data/schema.json`)
3. ต้องย่อให้มนุษย์อ่าน → ใช้ `verdict_short`, `capital_rule`, `returns[]`

## กติกาบังคับ (hard rules)
- **อย่า quote ตัวเลขโดยไม่รัน** `bash tools/verify.sh` — ตัวเลข usage/ราคา/balance เปลี่ยนรายวัน; `stale_risk` บอกไว้ต่อ record
- **`unverified[]` คือเส้นแดง**: ห้ามเปลี่ยนสิ่งที่ยังวัดไม่ได้ให้เป็นข้อสรุปเชิงบวก หรือบอกว่า "ไม่มีข้อมูล = น่าจะโอเค"
- **คำเคลมของแพลตฟอร์ม ≠ หลักฐาน**: `trust_evidence[]` มีเฉพาะสิ่งที่วัดเอง (RPC/merkle/source/ตลาด) เท่านั้น
- `needs_recheck: true` → หลักฐานไม่ครบ (round แรกไม่ได้ persist raw) → re-derive ก่อนอ้างหรือก่อนแนะนำเงิน
- คำแนะนำเรื่องเงินต้องมาจาก `cost_of_entry_usd`, `returns[]`, `max_sane_budget_usd`, `capital_rule` — ห้ามคิดตัวเลขใหม่เอง
- ทุก record ต้องมี `unverified[]` และ `watch[]` ไม่เช่นนั้น build จะ fail

## ถ้าจะเขียน/อัปเดต
1. แก้ dict ใน `tools/data_renaiss.py` | `tools/data_netnet_pullfun.py` | `tools/data_older.py` (+ `tools/data_meta.py` สำหรับ field 7/งบ/วันตรวจ)
2. `python3 tools/build.py` — จะ validate ให้ (ครบ 10 ฟิลด์, score 0-10, `returns[]` เรียงตามงบ, `unverified` ไม่ว่าง)
3. commit ทั้ง source และ generated files (repo นี้ตั้งใจให้ generate output ถูก commit ไว้เพื่อ agent ที่อ่านโดยไม่ต้องรัน Python)

### รูปแบบ record ที่ต้องคงไว้
```json
{{
  "name": "...", "links": {{ "x": "https://x.com/...", "site": "..." }},
  "score": {{ "interest": 8.5, "trust": 8.0 }},
  "field2_interest": "เหตุผลว่าทำไมได้คะแนนนี้",
  "trust_evidence": ["on-chain: ...", "source: ...", "market: ..."],
  "model": "สถาปัตยกรรม 3 ชั้น ...",
  "how_to_play": ["ตรวจก่อน ...", "เข้า ...", "ออก ..."],
  "risks": ["..."],
  "value_for_money": "จ่าย X ได้ Y",
  "house_edge": [{{ "machine": "...", "price_usd": 28, "ev_usd": 31.0, "ev_over_price": "+10.7%", "instant_flip_net_pct": -5.9 }}],
  "opportunity": "...",
  "returns": [{{ "budget_usd": 100, "note": "...", "expected_usd": -6.0 }}],
  "max_sane_budget_usd": 1000, "capital_rule": "...",
  "history": ["2026-06-18: ..."],
  "technical": {{ "onchain": [{{ "item": "...", "addr": "0x...", "finding": "..." }}], "api_endpoints": [] }},
  "verdict_short": "...",
  "unverified": ["..."], "watch": ["..."], "sources": ["..."],
  "stale_risk": "medium", "needs_recheck": false
}}
```

## สกอร์ = rubric (docs/methodology.md)
on-chain verifiability 25 + custody/funds proof 20 + real usage 20 + legal entity 15 + tokenomics/house edge 10 + team/backing 10 → ×10 เป็นสเกล 0-10

## เวลาจะเพิ่มโปรเจกต์ใหม่ (checklist ที่ใช้จริงกับ 8 ตัวนี้)
1. X profile: follower/tweets/join date/verified badge — นับ account ที่เกี่ยวข้องด้วย
2. โดเมน: RDAP/whois (`.fun`/`.capital` มักไม่ตอบ → ให้บันทึกว่า "ตรวจไม่ได้")
3. raw HTML + JS bundle: grep หา `0x[0-9a-f]{{40}}`, `contract`, `merkle`, `ethers|viem|wagmi` → ถ้า 0 = Web2 store
4. API: อ่าน `/openapi.json` ก่อนเดา path (path ที่เดาเอง 404 เกือบหมด)
5. On-chain: `totalSupply/ownerOf/balanceOf/paused/admin/code` + custody split + stablecoin balance ใน contract
6. Fairness: merkle root ต่อ set, `cardCount × allCardDrawnSetCount` = lifetime pulls (pull-history API ถูก capped)
7. ตลาด: CoinGecko/DexScreener (price/vol/liq/FDV) — liq/MC < 10% = ห้ามถือยาว
8. ToS/Privacy: entity + เขตอำนาจศาล + arbitration/KYC/geo-block
9. เงิน: คำนวณ EV ต่อหน่วย, haircut, round-trip cost, slippage ตามขนาด order จริง
10. เขียน `unverified[]` ให้ตรงข้ามกับ `trust_evidence[]` — สิ่งที่ยืนยันไม่ได้ต้องถูกเขียนไว้

## verify & push
- `bash tools/verify.sh` — re-check live (ต้องต่อเน็ตได้)
- `bash tools/push-github.sh yourname/crypto-due-diligence` — สร้าง repo + push (ใช้ `GITHUB_TOKEN`; repo นี้ไม่มีสิทธิ์ของใครฝังอยู่)
"""


def schema_json():
    return {
     "$schema": "http://json-schema.org/draft-07/schema#",
     "$id": "https://example.invalid/crypto-due-diligence/data/schema.json",
     "title": "Crypto/NFT/points due-diligence record",
     "description": "One file per project at data/projects/<slug>.json. Generated by tools/build.py; edit tools/data_*.py instead. The 10 required reader fields are documented in x_reader_fields.",
     "type": "object",
     "additionalProperties": False,
     "x_reader_fields": [{"n": n, "field": d, "keys": k} for n, d, k in FIELDS],
     "required": REQUIRED + ["needs_recheck", "schema_version"],
     "properties": {
      "slug": {"type": "string", "pattern": "^[a-z0-9-]+$"},
      "schema_version": {"type": "string"},
      "name": {"type": "string", "minLength": 1},
      "aliases": {"type": "array", "items": {"type": "string"}},
      "rank": {"type": "integer", "minimum": 1},
      "status": {"type": "string"},
      "links": {"type": "object", "required": ["x"], "properties": {
         "x": {"type": ["string", "null"], "description": "official X/Twitter URL or null when the handle was never confirmed"},
         "site": {"type": ["string", "null"]}, "docs": {"type": ["string", "null"]},
         "api": {"type": ["string", "null"]}, "related": {"type": "array", "items": {"type": "string"}}},
         "additionalProperties": True},
      "chain": {"type": "string"}, "legal_entity": {"type": "string"},
      "score": {"type": "object", "required": ["interest", "trust"], "properties": {
         "interest": {"type": "number", "minimum": 0, "maximum": 10},
         "trust": {"type": "number", "minimum": 0, "maximum": 10},
         "breakdown": {"type": "object"}}, "additionalProperties": True},
      "field2_interest": {"type": "string"},
      "trust_evidence": {"type": "array", "minItems": 1, "items": {"type": "string"},
         "description": "only self-verified observations (RPC/source/market/API). Platform marketing must not appear here."},
      "model": {"type": "string"},
      "how_to_play": {"type": "array", "minItems": 1, "items": {"type": "string"}},
      "risks": {"type": "array", "minItems": 1, "items": {"type": "string"}},
      "value_for_money": {"type": "string"},
      "house_edge": {"type": "array", "items": {"type": "object", "properties": {
          "machine": {"type": "string"}, "component": {"type": "string"}, "price_usd": {"type": "number"},
          "ev_usd": {"type": "number"}, "ev_over_price": {"type": "string"}, "instant_flip_net_pct": {"type": "number"},
          "value": {"type": "string"}, "note": {"type": "string"}, "tier_buyback_floor_usd": {"type": "array"}},
          "additionalProperties": True}},
      "cost_of_entry_usd": {"type": "number", "minimum": 0},
      "opportunity": {"type": "string"},
      "returns": {"type": "array", "minItems": 4, "items": {"type": "object", "required": ["budget_usd"],
          "properties": {"budget_usd": {"type": "number"}, "note": {"type": "string"}, "expected_usd": {"type": "number"}},
          "additionalProperties": True}},
      "max_sane_budget_usd": {"type": "number", "minimum": 0},
      "capital_rule": {"type": "string"},
      "history": {"type": "array", "minItems": 1, "items": {"type": "string"}},
      "technical": {"type": "object", "required": ["onchain"], "properties": {
         "onchain": {"type": "array", "minItems": 1, "items": {"type": "object", "required": ["item", "finding"],
             "properties": {"item": {"type": "string"}, "addr": {"type": "string"}, "finding": {"type": "string"}},
             "additionalProperties": True}},
         "api_endpoints": {"type": "array", "items": {"type": "string"}},
         "accounts": {"type": "object"}, "market": {"type": "object"}}, "additionalProperties": True},
      "verdict_short": {"type": "string", "minLength": 20},
      "unverified": {"type": "array", "minItems": 1, "items": {"type": "string"}},
      "watch": {"type": "array", "minItems": 1, "items": {"type": "string"}},
      "needs_recheck": {"type": "boolean"},
      "stale_risk": {"type": "string", "enum": ["low", "medium", "high"]},
      "stale_risk_note": {"type": "string", "description": "what exactly goes stale and how fast"},
      "verified_on": {"type": "string"},
      "sources": {"type": "array", "minItems": 1, "items": {"type": "string"}},
      "generated_from": {"type": "string"},
     }}


def write(path, text):
    p = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    io.open(p, "w", encoding="utf-8", newline="\n").write(text)
    return p


def main():
    check_only = "--check" in sys.argv
    recs = load()
    problems = validate(recs)
    if problems:
        print("VALIDATION FAILED:")
        for p in problems:
            print("  -", p)
        raise SystemExit(1)
    if check_only:
        print(f"OK: {len(recs)} records validate against {len(REQUIRED)} required keys")
        return
    written = []
    for r in recs.values():
        written.append(write(f"data/projects/{r['slug']}.json", json.dumps(to_json_record(r), ensure_ascii=False, indent=2) + "\n"))
        written.append(write(f"data/projects/{r['slug']}.md", md_for(r)))
    written.append(write("data/index.json", json.dumps(index_for(recs), ensure_ascii=False, indent=2) + "\n"))
    written.append(write("docs/schema.json", json.dumps(schema_json(), ensure_ascii=False, indent=2) + "\n"))
    rows = csv_rows(recs)
    p = os.path.join(ROOT, "data", "scorecard.csv")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with io.open(p, "w", encoding="utf-8-sig", newline="") as fh:
        csv.writer(fh).writerows(rows)
    written.append(p)
    written.append(write("README.md", readme(recs)))
    written.append(write("llms.txt", llms(recs)))
    written.append(write("AGENTS.md", agents_md(recs)))
    print(f"built {len(written)} files from {len(recs)} records")
    for f in sorted(written):
        print("  ", os.path.relpath(f, ROOT))


if __name__ == "__main__":
    main()
