# -*- coding: utf-8 -*-
"""NetNet ($NET) + Pull.Fun ($TAKO) records — measured live 2026-09-30 on Robinhood Chain (chainId 4663).
EDIT HISTORY: an earlier draft mis-attributed NetNet to (Base, netnet.fi) with an invalid 0x address,
and $TAKO to (Monad, CoinGecko id=tako). Both were corrected after re-deriving from
netnet.capital docs + the app bundle + the Robinhood Chain RPC + CoinGecko/DexScreener.
2026-10-01: post-audit cleanup — fixed garbled fragments (both records), fixed pullfun EV@$100 typo,
added instant-flip numbers to pullfun machines, unified $TAKO position cap with the budget ceiling."""

PROJECTS = {}

RHOD = "https://robinhoodchain.blockscout.com"

PROJECTS["netnet"] = dict(
 slug="netnet",
 name="NetNet Capital Management ($NET)",
 aliases=["NetNet", "The NetNet Reserve Fund", "NET Token"],
 legal_entity="NetNet Capital Management (self-described; the prospectus is pseudonymous). No registered entity is disclosed anywhere in docs or the bundle.",
 chain="Robinhood Chain (chainId 4663). RPC: https://rpc.mainnet.chain.robinhood.com | explorer: " + RHOD,
 links=dict(x="https://x.com/netnetcap",
            site="https://netnet.capital",
            docs="https://docs.netnet.capital",
            related=["https://app.netnet.capital", "https://superstore.netnet.capital",
                     "https://play.netnet.capital", "https://turbo.netnet.capital",
                     "https://x.com/netnetXdev", "https://t.me/netnetcap"]),
 score=dict(interest=7.5, trust=7.0), rank=2, status="live",
 verdict_short=("Reserve fund สไตล์ OlympusDAO v1 บน Robinhood Chain ที่โปร่งใสเกินมาตรฐานโครงการแนวนี้: มี prospectus ฉบับจริงบอกสูตร RFV = liquidUSDG + morphoPosition*(1-2%) + 2*sqrt(x*y)*lpShare, "
   "มีตาราง contract พร้อม provenance ของแต่ละ deployment — เรียกทุกตัวจริงผ่าน RPC และตัวเลขตรงกันหมด (USDG ใน Treasury $6.69M + $14.92M ใน Steakhouse Morpho vault รวม ~$21.6M รองรับ backing $173.46/NET ซึ่งนำไปตรวจซ้ำเองได้ทั้งหมด); "
   "แต่ราคาตลาด $435.98 = premium ~2.51x NAV และทั้งระบบถูกคุมด้วยกุญแจคนเดียว (team multisig 1-of-1) ซึ่งเอกสารเองยอมรับ"),
 field2_interest=("7.5/10 — โปรเจกต์เดียวในชุดนี้ที่เอกสาร+contract ตรงกันระดับที่ re-derive ทุกเลขได้ด้วยมือ; "
   "หักคะแนนที่ float เล็กมาก (MC $2.10M บน FDV $53.6M = 96.1% ไม่หมุน), premium ~2.51x NAV และ 1-of-1 custody"),
 trust_evidence=[
  "on-chain (RPC rpc.mainnet.chain.robinhood.com 2026-09-30): NET.name()='NetNet', NET.symbol()='NET', decimals=9, totalSupply=123,035.12 NET, NET.treasury()=0x04822EA321A0DEE6F40656172F29312104855d66",
  "on-chain: Treasury ถือ USDG สด $6,692,428.19; Treasury ถือ share ของ Steakhouse Morpho USDG vault (0xBeEff033F34C046626B8D0A041844C5d1A5409dd) convertToAssets = $14,923,520.98 => รวม ~$21,615,949 เทียบกับ rfv() ~$21,342,199 ต่างกัน < 1.3%",
  "on-chain: Treasury.backingPerToken() = 173.4643 (18dec scaled) => NAV ~$173.46 และราคาตลาด CoinGecko $435.98 => premium ~2.51x",
  "on-chain: team multisig 0x3Bb7A23316f82C0e984fA2E784846d8928a35f42 -> getThreshold()=1 และ getOwners()=[กระเป๋าเดียว 0xe7e867518c5B3d929CA63622f314FF9Dc60E96f6] => 1-of-1 ตรงที่ prospectus ยอมรับเองว่าต่ำกว่า 2-of-3 ของสเปกตัวเอง",
  "docs: มี prospectus page ครบทุก desk (Real World Bonds, Loopback, Predict, WinNET, CLIMB INC, Superstore, COINflip, SPACEX INVADERS, MSFT FLIGHT SIMULATOR, TURBO, TURBO BLACKJACK, THE BOARD MEETING, BASKETS, THE BOOK, NET ADVANCE, THE BUTTON) และหน้า official-channels ระบุชัดว่า 'IF A CHANNEL IS NOT ON THIS PAGE, IT IS NOT OURS'",
  "app bundle (app.netnet.capital/assets/index-C854Y_6l.js, 1.26 MB): มี contract map พร้อมข้อความ 'HUMAN-VERIFIED' + tx hash + block ของแต่ละ deployment (เช่น advanceDesk: create tx 0xaebf8d3c..., block 72453275)",
  "market: CoinGecko id=netnet: price $435.98, MC $2,103,280, FDV $53,599,297, circulating 4,824.28 (3.9%), total supply 122,913.62; ATH $1,887.55 (2026-08-29), ATL $15.83 (2026-07-27), 24h +2.3%, 7d -37.8%, 30d -62.7%",
  "correction: บันทึกรอบก่อนระบุ chain=Base, site=netnet.fi, contract=0x552eC46bEBb51734Bb67d56DdB1a5CB95224Gc96 (มี 'G' ไม่ใช่ hex) — แก้แล้วดังนี้"],
 model=("Reserve fund + desk network (mirroring OlympusDAO v1): Core = NET token, rebasing sNET, Treasury (sole minter, custodian), BondDepository, Distributor, GenesisBond, InverseBond (buyback), PremiumSeller, TaxCollector, pTEAM; "
   "Reserves = USDG เท่านั้น; idle treasury deploy เข้า Morpho (Steakhouse USDG) ด้วย formula cap 70% ที่ not-admin-tunable; "
   "รอบนอกเป็น 'desks' แต่ละตัวมี prospectus page: Real World Bonds (Equity Desk), Loopback (Lombard credit), Predict (Weekly Treasury Market), WinNET prize draw, CLIMB INC, Superstore (randomized-payout packs), COINflip, SPACEX INVADERS (reverse-plinko), MSFT FLIGHT SIMULATOR (crash game), TURBO, TURBO BLACKJACK, THE BOARD MEETING (PvP), BASKETS, THE BOOK (sports book), NET ADVANCE, THE BUTTON — หลายตัวระบุ 18+"),
 how_to_play=[
  "อ่านฟรีก่อนจ่าย: (a) docs.netnet.capital/treasury (สูตร RFV/NAV + Morpho cap) (b) เรียก on-chain (abi links ใน docs/evidence.md) (c) เช็ก official-channels ให้ตรงเว็บ 100% (d) เช็ก market cap vs FDV คือ 3.9% float",
  "เข้า: bridge ผ่าน Robinhood Chain portal → ซื้อ NET หรือผ่าน play/turbo desk UI — แต่เอกสารเขาเองบอกว่าเข้าที่ใกล้ NAV จะ preserve capital มากกว่า premium",
  "ออก: อย่าเข้าเมื่อ premium สูงอยู่แล้วเพื่อหวังออกเร็ว (tax 5%+5% + premium erosion กินเงินก่อนดอก)"],
 house_edge=[
  dict(component="swap tax buy+sell (pool mapped)", value="5% + 5% => round trip ~9.75% (ก่อน slippage)"),
  dict(component="premium to NAV", value="2.51x (ซื้อ $435.98 เพื่อได้ backing $173.46) — ถ้า NAV ไม่โต premium จะดูดกำไรทั้งหมด"),
  dict(component="1-of-1 custody", value="กุญแจคนเดียวทั้งระบบ — prospectus ยอมรับเองว่า 'below the 2-of-3 the fund's own specification recommends'"),
  dict(component="float tiny", value="4,824 of 122,914 NET circulating => order เล็กก็ขยับราคา"),
  dict(component="18+ arcade", value="หลาย desk เป็น gambling — เสี่ยงถูกจำกัดตามประเทศของผู้ใช้"),
  dict(component="no public audit", value="bundle มี label 'HUMAN-VERIFIED' provenance แต่ไม่มี auditor ภายนอกที่เปิดเผยชื่อ")],
 returns=[
  dict(budget_usd=0, what="อ่าน/verify ฟรี", note="ตรวจทุกอย่างได้ฟรีทั้ง docs + RPC ไม่ต้องใส่เงิน", expected_usd=0),
  dict(budget_usd=100, what="เข้า-ออกเร็วทดสอบระบบ", note="เสีย ~9.75% จาก tax 5%+5% โดยไม่พิจารณา yield", expected_usd=-9.75),
  dict(budget_usd=500, what="ถือ 8-16 วัน", note="rebase เริ่มมีผลแต่ premium ยังกินอยู่; ต้องถือจน index ชดเชย tax + premium", expected_usd=-48.75),
  dict(budget_usd=1000, what="position เล็กเมื่อเทียบ float", note="เริ่มเป็นสัดส่วนของ float 4,824 NET — ราคาเด้งเร็วทั้งซื้อและขาย", expected_usd=-97.5),
  dict(budget_usd=5000, what="ไม่แนะนำ", note="ออกยาก: slippage เพิ่มชัดเพราะพูลและ float เล็ก", expected_usd=-487.5),
  dict(budget_usd=10000, what="ห้ามเข้างบนี้", note="float น้อยมาก — คุณจะกลายเป็น size ของทั้งตลาด", expected_usd=-975.0)],
 opportunity=("อย่างน้อยโครงสร้างนี้เข้าใจได้: เมื่อ premium ใกล้ 1.0 คุณซื้อ NAV ในราคาใกล้ 1 NET ต่อ 1 USDG; และถ้า NAV โต (จาก desk revenue + treasury yield) ตัวเลขรองรับขึ้นตามจริง — ตรวจได้ผ่าน RPC; "
   "โอกาสจริงคือ (1) รอ premium < 1.1 แล้วเข้า (2) yield จาก staking/liquidity desks ที่เปิดแล้วบางส่วน ถ้าเลือกเข้าตำแหน่งที่ไม่ premium"),
 risks=[
  "**1-of-1 custody**: team multisig = signer เดียว — breach ครั้งเดียว = ทั้งระบบ (prospectus ยอมรับเอง)",
  "market float เล็ก: MC $2.1M vs FDV $53.6M => 96.1% ไม่หมุน — volume/on-paper มากกว่าขนาดซื้อขายจริง",
  "premium ~2.51x NAV: ถ้า NAV ไม่โต premium นี้คือต้นทุนที่คุณเสียทันทีทั้งหมด",
  "swap tax 5%+5% (~9.75% round trip): ทำให้การเข้า-ออกโดยไม่มี yield ทำงาน ติดลบตั้งแต่ต้น",
  "18+ desks: ห้องการพนันหลายตัว — เสี่ยงถูกจำกัด/ผิดกฎหมายตามประเทศของผู้ใช้",
  "ไม่มี audit ฉบับสาธารณะ (bundle มีแค่ label 'HUMAN-VERIFIED' จากทีมเอง)",
  "ช่องทางการ communication จำกัดโดยเจตนา: official-channels เท่านั้น — นอกลิสต์นั้นเขาประกาศเองว่าเป็น fake ทั้งหมด"],
 history=[
  "2026-04-07 เปิด X @netnetcap ตามบันทึกที่รวบรวม",
  "2026-07-14 bundle log: deploy ที่ block 9337409",
  "2026-07-23 bundle: VERSION()=1.4.1",
  "2026-07-27 ATL $15.83",
  "2026-08-29 ATH $1,887.55",
  "2026-09-09 attestation: commit ca83c8b4 ณ block 72453275 (Advance Desk)",
  "2026-09-23 bundle note: 'shifted by the architect at the human's instruction'",
  "2026-09-25 deploy advanceDesk: create tx 0xaebf8d3c8dad4a79ef044091243bf4b6ae01e621bf6f1f8a120f9470370c9dbe (provenance ใน bundle)",
  "2026-09-30 correction (เราอยู่ที่นี่): แก้ chain Base→Robinhood; แก้ NET address ที่ผิด (มี 'G' ซึ่งไม่ใช่อักขระ hex) เป็น 0xca9c…; re-verify ทุกตัวผ่าน RPC",
  "2026-10-01 post-audit: audit ภายนอกทักข้อความเพี้ยนในไฟล์นี้ — แก้สะอาดแล้วเท่าที่ตรวจใจกับหลักฐานเดิมได้"],
 technical=dict(onchain=[
   dict(item="NET token", addr="0xca9c78dd337a67f6e0077f65f5e9218719d30edf",
        finding="name NetNet | symbol NET | decimals 9 | totalSupply 123,035.12 (เรียกจริง) | treasury() → 0x04822E…"),
   dict(item="Treasury", addr="0x04822Ea321A0DEE6F40656172F29312104855d66",
        finding="USDG.balanceOf=$6,692,428.19 | rfv()≈$21.34M (18dec) | backingPerToken()=173.4643 (18dec)"),
   dict(item="Morpho Steakhouse USDG vault", addr="0xBeEff033F34C046626B8D0A041844C5d1A5409dd",
        finding="treasury.valueOf → convertToAssets = $14,923,520.98 (idle USDG เก็บอยู่ที่นี่ตาม 70/30 cap)"),
   dict(item="team multisig (1-of-1)", addr="0x3Bb7A23316f82C0e984fA2E784846d8928a35f42",
        finding="getThreshold()=1, getOwners()=[0xe7e86751… ตัวเดียว] — ตรง prospectus"),
   dict(item="USDG stablecoin", addr="0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
        finding="decimals 6; totalSupply ≈ $687M — reserve asset หลักของระบบ"),
   dict(item="Origami hOHM (ไม่ใช่ NET)", addr="0x76Cf788606F3d968B93B8A243D0e185C974EE407",
        finding="name 'Origami hOHM' symbol hOHM decimals 18 — ระวังอย่าไปตีความรวมว่าเป็น NET"),
   dict(item="advanceDesk", addr="0xDe9df88ABA59b644D4d7f6305e52aB982A3cFCac",
        finding="provenance ใน bundle: deploy block 72453275 + create tx hash จริง — ใช้ยืนยัน legitimacy ของ desk นี้ได้"),
   dict(item="auditor", finding="ไม่มี — bundle ใช้ label 'HUMAN-VERIFIED' จากทีมเองเท่านั้น ไม่มีชื่อบริษัท audit ใน docs")],
   api_endpoints=["https://docs.netnet.capital/treasury (RFV/NAV formula)",
                  "https://app.netnet.capital (Shareholder services)",
                  "https://netnetdesk-proxy-production.up.railway.app (backend — /health public)",
                  RHOD + "/token/0xca9c78dd337a67f6e0077f65f5e9218719d30edf"],
   accounts=dict(x=dict(handle="@netnetcap"), dev=dict(handle="@netnetXdev"), telegram=dict(handle="t.me/netnetcap")),
   market=dict(id="netnet", price=435.98, mc=2103280, fdv=53599297, circ=4824.28, total=122913.62,
               ath=1887.55, ath_date="2026-08-29", ath_change_pct=-76.9,
               atl=15.83, atl_date="2026-07-27", chg_24h=2.3, chg_7d=-37.8, chg_30d=-62.7)),
 unverified=["ชื่อบริษัท/registration ของ NetNet Capital Management",
  "ตาราง lock/vesting ของ supply 96.1% ที่ไม่หมุน (ทำไม FDV ไม่ตก?) — เขาไม่ publish",
  "audit ใด ๆ ที่เปิดเผยสาธารณะ",
  "holder concentration (Blockscout api/v2 ผ่าน Cloudflare)",
  "ที่ตั้ง custodian ของ RWA sleeve นอก USDG — prospectus อ้างถึงแต่ไม่มีหลักฐานแสดงบนหน้าเว็บ"],
 watch=["premium < 1.1 (เข้า)", "การปรับเปลี่ยน Morpho cap (เช่น 60/40)", "การเปลี่ยน 1-of-1 เป็น 2-of-3", "การประกาศ audit", "ช่องทาง fake บนเชนอื่น"],
 sources=["https://docs.netnet.capital/treasury", "https://docs.netnet.capital/mechanism", "https://docs.netnet.capital/official-channels", "https://docs.netnet.capital/team",
  "https://app.netnet.capital", "https://api.coingecko.com/api/v3/coins/netnet", RHOD + "/token/0xca9c…", "rpc.mainnet.chain.robinhood.com eth_call"],
 stale_risk="high",
 stale_risk_note="price/premium/treasury composition เปลี่ยนราย epoch 8 ชม.; backingPerToken ต้องเรียกใหม่ทุกครั้งที่ใช้")


PROJECTS["pullfun"] = dict(
 slug="pullfun",
 name="Pull.Fun (+ $TAKO)",
 aliases=["pull.fun", "PullFun", "TAKO points"],
 legal_entity="ไม่พบชื่อนิติบุคคลใน ToS — ใช้ '© Pull Fun 2026', email legal@pull.fun, กฎหมาย Delaware + arbitration",
 chain="ไม่มี smart contract ฝั่งเกม (ระบบเป็น DB ทั้งหมด) — มีแค่ $TAKO อยู่บน Robinhood Chain (chainId 4663) ตรวจวันนี้",
 links=dict(x="https://x.com/pulldotfun", site="https://pull.fun", docs=None, api="https://api.pull.fun/openapi.json",
            related=["https://x.com/takopull", RHOD + "/token/0xd6c0651a0c3f24BBF2794187285a66Da753A1D79",
                     "https://www.geckoterminal.com/robinhood/pools/0x0db676195d2da690afe67ff27444d941bcd7c056e2f512f40eb14620f3f0ead8"]),
 score=dict(interest=6.5, trust=4.5), rank=3, status="live (store; โทเคน ~8 วัน)",
 verdict_short=("ร้านเปิด pack การ์ดสแล็บจริงที่จริงจังด้าน UX — odds เปิดเผย, fair commit-reveal (off-chain), KYC, Stripe, ToS มีเนื้อหา — "
   "แต่ระบบทั้งหมดเป็น Web2: JS bundle 3.27 MB (71 chunks) มี 0 contract address สำหรับฝั่งเกม/คลัง และตัวเขาเองยอมรับว่าไม่พิสูจน์ inventory ได้; "
   "ด้านนักลงทุนคือโทเคนอายุ 7 วันบน Robinhood Chain: FDV $504,093, reserve $81,944, vol24 $3,913 (16 buys / 14 sells ใน 24 ชม.)"),
 field2_interest="product 6.5/10 | token 2/10 — แยกแยะให้ชัด: app แข็งแรงกว่า peer ในหมวดเดียวกัน; ส่วนโทเคนเป็นเดิมพันอายุ 7 วันที่ liquidity ยังตื้น",
 trust_evidence=[
  "JS bundle 3.27 MB (71 chunks): grep ครบหลัง curl ใหม่ (file ไม่ persist ต้องทำใหม่ทุกครั้ง) => 0 contract addresses สำหรับ gacha/custody, ไม่มี ethers/viem/wagmi ที่ส่วนของเกม => store แบบ Web2 บน DB ล้วน",
  "site admit (ใน FAQ): ระบบ provably-fair ของเขา 'does not prove physical inventory or shipping' — ตรงขนาดนี้ยังต้องยอมรับว่าเชื่อฝั่งคลังไม่ได้แม้ odds จะพิสูจน์ได้",
  "off-chain provable fair (ใน ToS + หน้า /proof, verify ที่เว็บเอง): server seed 32 bytes, commitment = SHA-256(seed), epoch/recharge ต่อ restock, ต่อ draw ใช้ HMAC-SHA256(version|packId|epochId|packPullIndex|clientNonce|poolSnapshotHash), poolSnapshotHash = hash ของ sorted JSON ของ pool คงเหลือ — แต่ไม่ลงบนเชน",
  "$TAKO (Robinhood, 0xd6c0651a0c3f24BBF2794187285a66Da753A1D79): พูลจริงเดียวที่มีนัยความหมาย — TAKO/WETH pair 0x0db676195d2da690afe67ff27444d941bcd7c056e2f512f40eb14620f3f0ead8 (created 2026-09-23 06:12 UTC), reserve $81,944, FDV $504,093, volume h24 $3,913, ผู้ซื้อ 16/ผู้ขาย 14 ใน 24 ชม.",
  "correction: บันทึกรอบก่อนระบุ chain=Monad + เชื่อม CoinGecko id 'tako' (ตัวนั้นเป็น Ethereum อีกเหรียญ 420B supply) — แก้เป็น Robinhood Chain แล้ว"],
 model=("E-commerce + gamification Web2 (Next.js/Vercel, Sanity CMS, PostHog/Sentry, Google Ads tag AW-18148001195, Stripe + เงินฝากคริปโตหลายเชน); "
   "รายได้จาก house margin บน odds (EV -10.6% ต่อ pack เฉลี่ยข้ามเครื่อง) + haircut ตอนขายการ์ดกลับ (90% ภายใน 1 ชม. → 80% หลังจากนั้น); "
   "โหมด yield ที่มีจริงคือ consignment: ฝากการ์ดเข้า pack pool แล้วกินส่วนแบ่งทุก pull ของผู้เล่นอื่น (APR คิดจาก 14 วันย้อนหลังของ pool, lifetime cap ล็อกตอน consign, ถ้าใบถูกดึงจ่าย 85% ของ market value — จ่ายเงินสด)"),
 how_to_play=["เปิดแอคเคาท์ + wallet → ฝาก crypto ผ่านเชนที่รองรับ (Robinhood/Base/Arbitrum/Solana/Hyperliquid) หรือฝาก USDG ตรง",
  "ซื้อ pack ที่ราคา $5 Champion / $10 / $15 / $21 / $33 — EV เฉลี่ย -10.6% ต่อ pack ตามตาราง odds/guaranteed return ที่เว็บประกาศเอง",
  "ทางออก: ขายกลับทันที 90% (ภายใน 1 ชม.) → 80% หลังจากนั้น, หรือถือเพื่อ consign yield, ถอนเงินโดน KYC + admin review"],
 house_edge=[dict(machine="Champion $5", price_usd=5, ev_usd=4.47, ev_over_price="-10.6%", instant_flip_net_pct=-19.5),
             dict(machine="PULL $10", price_usd=10, ev_usd=8.94, ev_over_price="-10.6%", instant_flip_net_pct=-19.5),
             dict(machine="PULL $15", price_usd=15, ev_usd=13.41, ev_over_price="-10.6%", instant_flip_net_pct=-19.5),
             dict(machine="PULL $21", price_usd=21, ev_usd=18.77, ev_over_price="-10.6%", instant_flip_net_pct=-19.5),
             dict(machine="PULL $33", price_usd=33, ev_usd=29.48, ev_over_price="-10.6%", instant_flip_net_pct=-19.5),
             dict(component="sell-back haircut / instant flip", value="ขายกลับภายใน 1 ชม. ได้ 90% ⇒ 0.894×0.90 = -19.5% net ต่อ pack (คอลัมน์ขวาสุดของตารางเครื่อง); หลัง 1 ชม. เหลือ 80% ⇒ 0.894×0.80 = -28.5% net — ยังไม่นับ market movement ของใบ"),
             dict(component="$TAKO market", value="reserve $81.9k ต่อ FDV $504k (16.3%) — เล่นได้แค่ระดับ speculation เล็ก ๆ เท่านั้น"),
             dict(component="geoblock / withdrawal", value="ToS ห้ามเขตการพนัน; ถอนเงินต้องผ่าน KYC + admin review (~24 ชม.)")],
 returns=[dict(budget_usd=10, what="ทดลอง pull 1-2 ใบ", note="คาดหวัง loss เล็กตาม EV -10.6%", expected_usd=-1.06),
          dict(budget_usd=50, what="เล่น ~5 ใบ", note="ค่าเฉลี่ย -10.6% ± variance ของ odds", expected_usd=-5.3),
          dict(budget_usd=100, what="เล่นเต็มโควต้า beginner ของซีซัน", note="ค่าเฉลี่ยยังติดลบ ตาม EV เดียวกัน", expected_usd=-10.6),
          dict(budget_usd=500, what="ทดสอบ consign yield", note="เสี่ยง counterparty เต็ม (escrow คลังตรวจไม่ได้)", expected_usd=-53.0),
          dict(budget_usd=1000, what="ฝากการ์ดเล่น APR ตามกลไก consignment ของเขา", note="ไม่แนะนำ — ไม่มี recourse หากของหาย", expected_usd=-106.0),
          dict(budget_usd=5000, what="ไม่ควรเข้า", note="position ใหญ่กว่า exit depth ในทุกสถานการณ์", expected_usd=-530.0)],
 opportunity=("ด้าน product: odds เปิดเผย + edge ต่ำสุดใน class จึงเป็นร้าน playing-for-fun ที่ถูกที่สุดในชุดที่ตรวจ; "
   "ด้าน token: ไม่มี utility/on-chain proof ให้ถือ — มีแค่การรอ Season 2 announcement ที่ไม่มีกำหนด; "
   "ถ้าบังคับจะเก็งกำไร $TAKO: จำกัด ≤$500 ต่อ position (~0.6% ของ reserve $81.9k) และ exit ทันทีเมื่อ reserve/MC < 10%"),
 risks=["คลังตรวจสอบไม่ได้: ไม่มี on-chain receipt/serial attestation; ถ้าเขาทิ้งของ คุณต้อง arbitration กับนิติบุคคลนิรนามในดีลาแวร์",
  "$TAKO มี reserve เพียง $81,944 ต่อ FDV $504,093 (16.3%) => การเข้า-ออก >= $5k ต้องลากราคาเอง",
  "ราคา -88% จากไฮวันแรก; volume h24 ต่ำมาก (~$3.9k ตามที่ตรวจ)",
  "geo/legal: ToS บล็อกเขตที่ห้ามการพนัน — ไทยมีข้อจำกัดเรื่องการพนันออนไลน์แทบทุกรูปแบบ; ตัดสินเองอย่างระมัดระวัง",
  "การถอนต้องผ่าน KYC + admin review (~24 ชม.) และไม่มีระบบคุ้มครองนักลงทุนใด ๆ",
  "confusion: มี 'TAKO' อื่นเต็มไปหมด (Ethereum 'Tako' 420B, token pump บน Solana, Pull.Fun clone บน Solana ด้วย) — ห้ามซื้อผิดเชน"],
 history=["2026-03-20 เปิด @pulldotfun",
  "2026-04-02 ToS ฉบับล่าสุด",
  "2026-09-10 เปิด @takopull",
  "2026-09-23 06:12 สร้างพูล TAKO/WETH บน Robinhood Chain",
  "2026-09-23 วันแรก: O $0.0001719 -> H $0.0042677 -> C $0.0008298, vol $933,452 (ชั่วโมงแรก $732,673) [recorded previous session]",
  "09-24 ถึง 09-27: -20.5, +22.5, -12.1, -2.0% | 09-28 -48.1 | 09-29 +20.7 | 09-30 $0.0005037, FDV $504,093, reserve $81,944",
  "correction 2026-09-30: แก้ chain=Monad -> Robinhood Chain (DexScreener/GeckoTerminal แสดงชัดว่าเป็น robinhood) + ลิงก์ CoinGecko id=tako ที่ผิด",
  "correction 2026-10-01: แก้ EV@$100 (-11.6 → -10.6), ลดเพดาน $TAKO ให้ตรงกับ max_sane_budget_usd, เพิ่ม instant-flip columns"],
 technical=dict(onchain=[
   dict(item="$TAKO token (มีจริงบนเชน) — แต่ไม่รับบท custody ใด ๆ ของเกม", addr="0xd6c0651a0c3f24BBF2794187285a66Da753A1D79",
        finding="grep bundle 3.27 MB ไม่พบ contract สำหรับฝั่งเกม; สิ่งเดียวที่อยู่บนเชนคือโทเคน + พูลของมันเอง"),
   dict(item="TAKO/WETH pool (หลัก)", addr="0x0db676195d2da690afe67ff27444d941bcd7c056e2f512f40eb14620f3f0ead8",
        finding="created 2026-09-23 06:12:01 UTC | price $0.000504093 | reserve $81,944.26 | FDV $504,093 | txns h24 16 buys/14 sells"),
   dict(item="TAKO/WETH pool (รอง), reserve $101.12", addr="0xba4186813eb1c6e6905b34b28de46c0b638a2fd94d6ded46d55d1293a37cb771",
        finding="พูลย่อยบนเชนเดียวกัน — reserve เล็กมาก ไม่มีนัยทางการเงิน"),
   ],
   api_endpoints=["/v0/fair/packs", "/v0/fair/packs/{onChainPackId}/sets", "/openapi.json (134 paths ตามที่ grep เมื่อ round ก่อน)",
                  RHOD + "/token/0xd6c0651a0c3f24BBF2794187285a66Da753A1D79",
                  "https://api.geckoterminal.com/api/v2/networks/robinhood/pools/0x0db6...80ead8"],
   accounts=dict(store=dict(handle="@pulldotfun", followers=5986, tweets=1121, joined="2026-03-20", verified=False),
                 token=dict(handle="@takopull", followers=2045, tweets=21, joined="2026-09-10", verified=False),
                 friends=dict(handle="@PullFunFriends",
                              note="ลิงก์จาก footer เว็บเขาเองชี้มาที่บัญชีนี้ แต่ตอนนี้ 404 — บันทึกเป็นหลักฐานว่า official links ขาดดูแล (ไม่ใช่ source ของรายงาน)"),
                 updates=dict(handle="@PullFunUpdates",
                              note="เช่นกัน — official link ชี้มาที่บัญชีที่ 404")),
   market=dict(token="$TAKO (Robinhood Chain)", price=0.0005037, fdv=504093, mc=503785, reserve=81944,
               vol_h24=3913, created="2026-09-23T06:12:01Z", source="GeckoTerminal + DexScreener 2026-09-30")),
 unverified=["อายุโดเมน .fun (RDAP เงียบ)", "จำนวน holder จริงของ $TAKO", "ว่า LP token ถูก lock หรือไม่", "จำนวน $TAKO ที่ claim แล้ว",
  "utility ของ $TAKO ในระบบ (ไม่มีที่เขียนไว้ทางการ)", "จำนวนสแล็บจริงในคลังของเขา", "ใคร own คลังเงินขณะใด"],
 watch=["liq/MC ratio (กฎ: <10% ห้าม hold ยาว)", "จำนวน pack ที่ปิดแล้วเผย seed ที่ /proof", "การประกาศ Season 2 / points ที่ติดต่อได้"],
 sources=["https://pull.fun", "https://pull.fun/en/terms", "https://pull.fun/en/faq",
  "https://www.geckoterminal.com/robinhood/pools/0x0db6...", "https://api.dexscreener.com/latest/dex/search?q=TAKO",
  RHOD + "/token/0xd6c0651a0c3f24BBF2794187285a66Da753A1D79"],
 stale_risk="high",
 stale_risk_note="price/reserve เปลี่ยนรายชั่วโมง; การแสดงผลของ points season เปลี่ยนโดยไม่ประกาศ; re-curl bundle ก่อน grep ทุกครั้ง (raw data ไม่ persist ข้าม session)")
